% -------------------------------------------------------------------
%  Generated by MATLAB on 2-May-2018 01:45:47
%  MATLAB version: 9.4.0.813654 (R2018a)
% -------------------------------------------------------------------
saveVarsMat = load('fake.mat');

A = [];

Aeq = [];

DV = 0.57077753091658046;

Dv1 = 0.10303636313008788;

Dv2 = 0.46774116778649261;

ans = 1.582530602898804;

b = [];

beq = [];

dv = saveVarsMat.dv; % <1x14401 double> too many elements

i = 18000;

lb = 3600;

options = saveVarsMat.options; % <1x1 optim.options.Fmincon> unsupported class

tau = 5697.1101704356943;

tau0 = 7200;

ub = 18000;

clear saveVarsMat;
